-- phpMyAdmin SQL Dump
-- version 4.9.5
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Tempo de geração: 26-Mar-2021 às 06:57
-- Versão do servidor: 10.4.14-MariaDB-cll-lve
-- versão do PHP: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `u668586037_fisiologia`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `questoes`
--

CREATE TABLE `questoes` (
  `id` int(11) NOT NULL,
  `nivel` int(2) NOT NULL,
  `fase` int(2) NOT NULL,
  `texto` text COLLATE utf8_unicode_ci NOT NULL,
  `opcao1` text COLLATE utf8_unicode_ci NOT NULL,
  `opcao2` text COLLATE utf8_unicode_ci NOT NULL,
  `opcao3` text COLLATE utf8_unicode_ci NOT NULL,
  `opcao4` text COLLATE utf8_unicode_ci NOT NULL,
  `opcao5` text COLLATE utf8_unicode_ci NOT NULL,
  `categoria` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
  `textoajuda` text COLLATE utf8_unicode_ci NOT NULL,
  `fotoajuda` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `foto` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `correta` int(1) NOT NULL,
  `corretaVouf` varchar(200) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Extraindo dados da tabela `questoes`
--

INSERT INTO `questoes` (`id`, `nivel`, `fase`, `texto`, `opcao1`, `opcao2`, `opcao3`, `opcao4`, `opcao5`, `categoria`, `textoajuda`, `fotoajuda`, `foto`, `correta`, `corretaVouf`) VALUES
(104, 1, 4, '<p><strong>O infundíbulo conecta o hipotálamo com a hipófise.</strong></p>', '', '', '', '', '', 'vouf', '', 'ajudaac77b100f9ccffcfb03b0156a02e3733..jpg', 'empty', 1, 'verdadeiro'),
(105, 1, 6, '<p>O sistema porta hipotalâmico-hipofisário, que fornece suprimento sanguíneo a adeno-hipófise, é constituído por ramos da carótida externa.</p>', '', '', '', '', '', 'vouf', '<p>Os peptídeos hipofisiotróficos liberados próximo à eminência mediana são transportados ao longo do pedículo infundibular até a adeno-hipófise, onde exercem seus efeitos fisiológicos. O suprimento sanguíneo da hipófise é constituído por ramos arteriais que cruzam e irrigam a adeno-hipófise.</p>', 'ajudace0feba65c6d18be866f12679f4e1987..jpg', 'empty', 0, 'falso'),
(106, 2, 1, '<p>Os neurônios magnocelulares são células neurossecretoras que produzem hormônios que serão transportados até a neuro-hipófise. No hipotálamo, essas células estão organizadas em núcleos, que nada mais é do que um aglomerado de corpos celulares. &nbsp;Os núcleos hipotalâmicos onde predominantemente se encontram as células magnocelulares são:</p>', 'Núcleo paraventricular e supra-óptico', 'Núcleo posterior e paraventricular', 'Núcleo supra-óptico e pré-óptico', 'Núcleo ventromedial e posterior', 'Núcleo supra-óptico e ventromedial', 'quest', '<p>Os neurônios magnocelulares tem a sua predominância nos núcleos paraventricular e supra-óptico, que através de seus axônios percorrem a eminência mediana para a formação do trato.&nbsp;</p><p>Existem dois tipos de neurônios que são cruciais no desempenho do hipotálamo: Os magnocelulares e os parvicelulares. Os magnocelulares fazem parte de dois núcleos, supraóptico e paraventricular que são grandes produtores de ocitocina e arginina vasopressina.</p>', 'ajuda289f39c6ec54ef0d0bba735fea863a7c..jpg', 'empty', 1, ''),
(107, 2, 5, '<p>Na adeno-hipófise existem células que serão estimuladas ou inibidas pelos neuro-peptídios secretados pelos neurônios parvicelulares e terá ação em sua atuação hormonal. Por exemplo, o neuro-peptídio GHRH estimula a célula ____________________, o TRH estimula a célula ________________, o GNRH ativa a célula ________________, o CRH ativa a célula ________________ e PRH ativa a célula __________________.</p>', 'Lactotropos, corticotropos, gonadotopos, tireotropos, somatotropos', 'Somatotropos, tireotropos, gonadotropos, corticotropos, lactotropos', 'Gonadtropos, lactotropos, cortictropos, somatotropos, tireotropos', 'Tireotropos, gonadotropos, corticotropos, somatotropos, lactotropos', 'Corticotropos, somatotropos, lactotropos, tireotropos, gonadotropos', 'quest', '', 'ajuda885c4c5393b82256dde69eb63c10f24d..jpg', 'empty', 2, ''),
(108, 2, 9, '<p>Os neurônios magnocelulares produzem hormônios que serão secretados pela neuro-hipófise. Quais são eles?</p>', 'Hormônio do crescimento e hormônio estimulante da tireoide', 'Hormônio vasopressina e hormônio luteinizante', 'Hormônio do crescimento e hormônio antidiurético', 'Hormônio folículo estimulante e hormônio adrenocorticotrófico', 'Hormônio ocitocina e hormônio antidiurético', 'quest', '<p>A ocitocina e a Arginina vasopressina são hormônios da neuro-hipófise que tem sua secreção controlada pelo neurônio magnocelular que através de vesículas, irá disponibilizar os hormônios nas terminações sinapticas.</p>', 'empty', 'empty', 5, ''),
(109, 3, 7, '<p>A eminência mediana é de extrema importância, uma vez que, é o local onde os terminais axônios dos neurônios hipotalâmicos liberam os neuro-peptídios envolvidos no controle da função endócrina da adeno-hipófise.</p>', '', '', '', '', '', 'vouf', '', 'ajuda609da26262359146e15d712509d7afc5..jpg', 'empty', 1, 'verdadeiro'),
(110, 4, 3, '<p>A secreção de GH aumenta durante o exercício, para a mobilização dos ácidos graxos do tecido adiposo e para auxiliar na manutenção da glicemia.</p>', '', '', '', '', '', 'vouf', '<p>A secreção de GH aumenta durante o exercício, para a mobilização dos ácidos graxos do tecido adiposo e para auxiliar na manutenção da glicemia.</p>', 'empty', 'empty', 1, 'verdadeiro'),
(111, 4, 5, '<p>Quais os órgãos-alvo do hormônio GH?</p>', 'Ossos, tecido adiposo, músculo esquelético, pâncreas, sistema imune', 'Ossos, tecido adiposo, músculo esquelético, fígado, pulmão', 'Ossos, tecido adiposo, músculo esquelético, rins, sistema imune', 'Ossos, tecido adiposo, músculo esquelético, baço, sistema imune', 'Ossos, tecido adiposo, músculo esquelético, fígado, sistema imune', 'quest', '<p>O GH irá atuar em vários órgãos porém com predominância em alguns. Ele estará na maturação óssea e muscular, nos fatores que regulam a insulina no fígado e também irá auxiliar na manutenção do nosso sistema imune.</p>', 'empty', 'empty', 5, ''),
(112, 5, 6, '<p>A Prl é um hormônio polipeptídico sintetizado e secretado pelos lactotrofos presentes na adeno-hipófise. A sua atuação se dá pela alta concentração de progesterona durante a ____________. A liberação de Prl em resposta à _____________ é um reflexo neuroendócrino clássico, também conhecido como reflexo de estimulação-secreção.</p>', 'Adolescência, idade', 'Ovulação, gestação', 'Gestação, sucção', 'Prática de atividade física, atividade ', 'Adolescência, prática de atividade física', 'quest', '<p>Um dos hormônios da adeno-hipófise é a prolactina. A prolactina (Prl) estimula o desenvolvimento da mama e a produção de leite durante a gestação. O ato de amamentar o bebê é um dos fatores de liberação neuroendócrina da Prl de forma reflexa.</p>', 'empty', 'empty', 3, ''),
(113, 5, 7, '<p>Quais são os locais mais bem caracterizados pela ação da prolactina?</p>', 'Rins e fígado', 'Glândula mamária e ovário', 'Ovário e testículos', 'Tireoide e suprarrenal', 'Tecidos do organismo', 'quest', '<p>A prolactina é um importante hormônio do corpo feminino. Ele irá gerar um estímulos ovarianos para a secreção de progesterona &nbsp; e nas glândulas mamárias que irá auxiliar na produção e ejeção do leite materno.</p>', 'empty', 'empty', 2, ''),
(114, 5, 8, '<p>Selecione a alternativa que melhor indica um dos principais efeitos fisiológicos da prolactina:</p>', 'Estimulação do crescimento da glândula mamária', 'Síntese de leite', 'Estimulação do desenvolvimento da glândula mamária', 'Manutenção da secreção do leite', 'Todas as alternativas estão corretas', 'quest', '<p>Os principais efeitos fisiológicos da Prl consistem na estimulação do crescimento e do desenvolvimento da glândula mamária, na síntese de leite e na manutenção da secreção de leite. A Prl estimula a captação da glicose e de aminoácidos, bem como a síntese das proteínas do leite b-caseína e a-lactalbumina, do açúcar do leite lactose e das gorduras do leite pelas células epiteliais da mama. Durante a gravidez, a Prl prepara a mama para a lactação. A produção e a secreção de leite são impedidas durante a gravidez pelos níveis elevados de progesterona.</p>', 'empty', 'empty', 5, ''),
(115, 5, 9, '<p>O aumento no nível de prolactina (PRL) circulante pode causar infertilidade feminina.</p>', '', '', '', '', '', 'vouf', '<p>Os pacientes com prolactinoma apresentam níveis elevados de Prl (hiperprolactinemia), secreção de leite (galactorreia) e disfunção reprodutiva (infertilidade). Na maioria dos casos, os agonistas da dopamina são extremamente efetivos para reduzir os níveis séricos de Prl, restabelecer a função gonadal, diminuir o tamanho do tumor e melhorar os campos visuais.</p>', 'empty', 'empty', 1, 'verdadeiro'),
(116, 6, 4, '<p>O hormônio luteinizante (LH) estimula a produção de testosterona pelas células de Leydig, sendo que a testosterona é o principal hormônio masculino. Em qual órgão esse hormônio é produzido?</p>', 'Hipotálamo', 'Testículos', 'Hipófise', 'Córtex da suprarrenal', 'Tireoide ', 'quest', '<p>O LH é o principal regulador da síntese de testosterona pelas células de Leydig. O FSH desempenha um importante papel no desenvolvimento do testículo imaturo, em particular pelo controle da proliferação das células de Sertoli e do crescimento dos túbulos seminíferos. Como os túbulos são responsáveis por cerca de 80% do volume do testículo, o FSH é de grande importância na determinação do tamanho dos testículos, que normalmente medem 4,1 a 5,2 cm de comprimento por 2,5 a 3,3 cm de largura no homem adulto. O FSH é importante no processo de iniciação da espermatogênese durante a puberdade, sendo necessário para a síntese da proteína de ligação dos androgênios pelas células de Sertoli e para o desenvolvimento da barreira hematotesticular.</p>', 'ajuda15eb5762fd8f0c6bcd3457af640ddbd9..jpg', 'empty', 2, ''),
(117, 6, 5, '<p>Assinale a alternativa que não representa uma função da testosterona em pessoas do sexo masculino:</p>', 'Desenvolvimento de testículos', 'Aumento da massa muscular', 'Aumento e maturação dos ossos', 'Aumento das glândulas mamárias', 'Todas as alternativas estão corretas', 'quest', '', 'ajuda4d2bc286263f692ad18bcc3bd7ede00c..jpg', 'empty', 4, ''),
(118, 6, 6, '<p>No sistema reprodutor feminino o hormônio luteinizante e o folículo estimulante estimulam a produção ovariana de ___________________ e ____________________, os dois principais hormônios envolvidos na regulação da função ovariana e no controle do ciclo reprodutivo.</p>', 'Estradiol, progesterona', 'Prolactina, estrogênio', 'Estrogênio, ocitocina', 'Ocitocina, progesterona', 'Progesterona, estrogênio', 'quest', '', 'ajudae5174cd49e297b461beb1f065199b513..jpg', 'empty', 5, ''),
(119, 6, 8, '<p>O corpo lúteo é um dos principais precursores dos hormônios femininos. Culminando assim, com suas principais ações fisiológicas.&nbsp;</p>', '', '', '', '', '', 'vouf', '<p>A fase lútea começa após a ovulação, com a reorganização dos remanescentes do folículo ovulatório e a formação do corpo lúteo. O corpo lúteo é um órgão endócrino transitório que produz progesterona e, em menor grau, estradiol e inibina A. Ele se encontra sob a regulação do LH. A fase lútea termina quando não ocorre fertilização e a sobrevida do corpo lúteo é mediada pela placenta.</p>', 'ajudae2d39d76846aa6565a1d1bdb7f93527a..jpg', 'empty', 0, 'falso'),
(120, 7, 1, '<p>O hormônio antidiurético (também conhecido como arginina vasopressina) que é produzido no hipotálamo e secretado pela hipófise posterior, é responsável pelo aumento da reabsorção de água pelos rins. Com isso, consegue modular o volume plasmático de sangue. Marque a alternativa que corresponde a um de seus feitos.</p>', 'Colabora para o aumento da pressão arterial', 'Diminui a pressão arterial por promover o aumento do volume plasmático', 'Diminui a resistência vascular', 'Aumenta a permeabilidade dos vasos esplâncnicos', 'Todas estão corretas', 'quest', '<p>A AVP, também conhecida como hormônio antidiurético (ADH, de antidiuretic hormone), constitui o outro neuropeptídeo sintetizado pelos neurônios magnocelulares do hipotálamo e liberado pela neuro-hipófise. O principal efeito da AVP consiste em aumentar a reabsorção de água por um aumento da permeabilidade à água nos túbulos convolutos distais e nos ductos coletores medulares do rim. O resultado consiste na produção de menores volumes de urina concentrada. Além disso, a AVP aumenta a resistência vascular.</p>', 'ajudaeabf9d90c3c648083da5ce4a43ee1441..jpg', 'empty', 1, ''),
(121, 7, 2, '<p>O ___________________ é o principal local-alvo de ação do ADH.&nbsp;</p>', 'Córtex suprarrenal', 'Átrio esquerdo do coração', 'Intestino delgado', 'ducto coletor do rim', 'Hipotálamo', 'quest', '<p>O principal efeito que o hormônio antidiurético tem no nosso corpo é a reabsorção de água. Isso ocorre através do aumento da permeabilidade à água nos túbulos convolutos distais e nos ductos coletores medulares do rim.</p>', 'ajuda7d0ed3f26ae204bdc783884507e53038..jpg', 'empty', 4, ''),
(122, 10, 8, '<p>As ações dos hormônios da tireoide não são sistêmicas, porém, de grande importância para o desenvolvimento, o crescimento e o metabolismo.</p>', '', '', '', '', '', 'vouf', '<p>Os hormônios da tireoide desempenham importantes papéis na manutenção da homeostasia e na regulação do consumo de energia. Seus efeitos fisiológicos, que são mediados em múltiplos órgãos-alvo, consistem principalmente em estimular o metabolismo e a atividade das células. As funções vitais desses hormônios, em particular no desenvolvimento, na diferenciação e na maturação, são ressaltadas pela deficiência mental grave observada em lactentes com deficiência da função dos hormônios tireoidianos durante a gestação.</p>', 'empty', 'empty', 0, 'falso'),
(123, 1, 1, '<p>O hipotálamo faz parte do epitálamo, que fica no diencéfalo.</p>', '', '', '', '', '', 'vouf', '<p>O hipotálamo faz parte do diencéfalo assim como o epitálamo.</p>', 'ajuda7dcfe78949a8345bfdceb820fcc791fe..jpg', 'empty', 0, 'falso'),
(124, 1, 2, '<p>O hipotálamo é a região do cérebro envolvida na coordenação das respostas fisiológicas de diferentes órgãos que, em conjunto, mantém a homeostasia. Para tal, o hipotálamo recebe informações do ambiente e de outras regiões do cérebro. Após ler essa afirmação, responda qual interação de estímulos entre hipotálamo e outros meios que não irá afetar a homeostasia da pessoa:</p>', 'Sono/vigília adequado', 'Medo', 'Ansiedade', 'Estresse', 'Nenhuma das alternativas', 'quest', '<p>Conforme a questão cita em seu enunciado, o hipotálamo é responsável pela coordenação das respostas fisiológicas de diferentes órgãos que em conjunto, mantém a homeostasia. Sendo assim, qualquer fator que afete o equilíbrio neuroendócrino irá modular a resposta hipotalâmica de forma negativa ou positiva.</p>', 'empty', 'empty', 5, ''),
(125, 7, 4, '<p>Como resultado da deficiência de ADH acontece uma produção de grandes quantidades de _______________.</p>', 'Saliva ', 'Lágrimas', 'Urina', 'Suor', 'Todas as alternativas estão corretas', 'quest', '<p>Quando a arginina vasopressina não está trabalhando de forma adequada, a quantidade total de urina que seria excretada em sua ausência acaba aumentando. Por exemplo, em um indivíduo sadio, são formados, em média, 180 L de filtrado glomerular por dia. Por conseguinte, sem a reabsorção mediada pela AVP de 10% da água filtrada nos ductos coletores distais, a produção de urina estaria próximo a 18 L/dia, o que representa uma quantidade 10 vezes maior que o volume de urina formada (1,5 a 2 L/dia) em condições normais.</p>', 'empty', 'empty', 3, ''),
(126, 7, 8, '<p>Qual o principal estímulo para liberação de ocitocina?</p>', 'Substratos energéticos metabolizáveis pela célula B pancreática', 'Níveis baixos de testosterona', ' Aumento da osmolaridade do plasma', 'Estímulos externos, como luz solar ou estresse', 'Estimulação mecânica do colo do útero pelo feto no final da gestação', 'quest', '<p>A responsividade do útero a ocitocina também é intensificada por um aumento na formação das junções comunicantes (gap junctions) entre as células musculares lisas, facilitando a condução dos potenciais de ação entre uma célula e outra, bem como pelo aumento na síntese da prostaglandina, um estimulante conhecido da contração uterina até o final da gestação. Todos esses fatores aumentam a atividade contrátil do miométrio em resposta à ocitocina ao final da gestação. A estimulação mecânica do colo do útero pelo feto no final da gestação constitui o principal estímulo para a liberação de ocitocina, que também é estimulada pelas contrações vigorosas do útero durante o reflexo de expulsão fetal.</p>', 'ajuda91e0d2725d17dc30c96fbd42c192b63c..jpg', 'empty', 5, ''),
(127, 8, 2, '<p>A neuro-hipófise é considerada uma extensão do hipotálamo.</p><p>Marque a alternativa que melhor explica essa afirmação.</p>', 'É considerada uma extensão, pois o hipotálamo se afunila para formar a porção infundibular da neuro-hipófise', ' Porque compartilham o mesmo sistema de irrigação.', 'Porque a neuro-hipófise é independente da adeno-hipófise', 'É considera uma extensão, porque todos os hormônios se localizam no hipotálamo', 'Por que os neurônios que cruzam o infundíbulo, secretam apenas neuropeptídios', 'quest', '<p>A eminência mediana é importante, visto que constitui o local onde os terminais axônicos dos neurônios hipotalâmicos liberam os neuropeptídeos envolvidos no controle da função da adeno-hipófise. Além disso, ela é atravessada pelos axônios dos neurônios hipotalâmicos que terminam na neuro-hipófise. Ela se afunila para formar a porção infundibular da neuro-hipófise (também denominada pedículo hipofisário ou infundibular). Em termos práticos, a neuro-hipófise ou hipófise posterior pode ser considerada uma extensão do hipotálamo.</p>', 'empty', 'empty', 1, ''),
(128, 8, 5, '<p>Sobre os hormônios hipotalâmicos, responda marcando a afirmação correta:</p>', 'Agem através de feedback negativo', 'Atuam com uma alça de retroalimentação positiva', 'Os hormônios gonadotrópicos atuam na modulação da resposta do hormônio modulador da gonadotrofina', 'A somatostatina é liberada pelo hormônio liberador de tireotrofina', 'Atuam de forma a contribuir com  a ação dos hormônios liberados na corrente sanguínea', 'quest', '<p>Os hormônios podem fornecer sinais ao hipotálamo para inibir ou estimular a liberação de hormônios hipofisiotróficos. Esse mecanismo de controle da regulação por retroalimentação negativa (ou positiva) consiste na capacidade de um hormônio de regular sua própria cascata de liberação. Por exemplo, conforme discutido mais detalhadamente no Capítulo 6, o cortisol produzido pela glândula suprarrenal pode inibir a liberação do CRH, inibindo, assim, a produção da pró-opiomelanocortina e do ACTH e diminuindo, consequentemente, a síntese de cortisol pela suprarrenal. Essa alça de controle hormonal e de regulação de sua própria síntese é de importância crítica na manutenção da homeostasia e na prevenção de doenças.</p>', 'empty', 'empty', 1, ''),
(129, 8, 7, '<p>O hormônio do crescimento (GH) aumenta durante o exercício, para a mobilização dos ácidos graxos do tecido adiposo e para auxiliar na manutenção da glicemia.</p>', '', '', '', '', '', 'vouf', '<p>Diversos efeitos promovidos pelo exercício físico são influenciados pelo GH, incluindo a redução no catabolismo proteico e a oxidação de glicose, concomitantemente ao aumento da mobilização de AGL (Ácidos Graxos Livres) do tecido adiposo, para gerar energia. Estes fatos sugerem o GH como importante hormônio liberado em diversas situações de estresse. No entanto, estudos demonstram que o GH também tem efeitos considerados como &quot;anabólicos&quot;, dentre os quais a promoção do balanço proteico positivo e o aumento na quantidade de massa muscular e na liberação de IGF-1 o qual está envolvido na estimulação do processo hipertrófico muscular.</p>', 'empty', 'empty', 1, 'verdadeiro'),
(130, 9, 4, '<p>Seria uma das consequências da hiperprolactinemia:</p>', 'Aumento da libido', 'Menstruação irregular', 'Aumento do volume na menstruação', 'Evitar processos tumorais na hipófise', 'Prevenir a disfunção erétil', 'quest', '<p>Os pequenos adenomas hipofisários podem produzir manifestações de excesso de produção de hormônios tróficos, enquanto os tumores mais volumosos podem causar sintomas neurológicos por efeito compressivo sobre a área da sela turca. Os pacientes com prolactinoma apresentam níveis elevados de Prl (hiperprolactinemia), secreção de leite (galactorreia) e disfunção reprodutiva (infertilidade) afetando o ciclo menstrual. Na maioria dos casos, os agonistas da dopamina são extremamente efetivos para reduzir os níveis séricos de Prl, restabelecer a função gonadal, diminuir o tamanho do tumor e melhorar os campos visuais. A hiperprolactinemia também pode decorrer da inibição da liberação de dopamina induzida por fármacos.</p>', 'empty', 'empty', 2, ''),
(131, 9, 5, '<p>O hormônio TSH estimula a tireoide a produzir os hormônios T4 e T3 . Quando o nível de TSH plasmático está alto, isso significa que os níveis de T4 e T3 estão baixos no sangue e quando o nível plasmático de TSH está baixo, significa que os níveis de T4 e T3 estão altos. Os baixos níveis de TSH sanguíneo podem causar hipertireoidismo e os altos níveis de TSH sanguíneo podem causar hipotireoidismo.</p>', '', '', '', '', '', 'vouf', '<p>Dica da questão: O indivíduo cuja função da tireoide está normal se encontra no chamado estado eutireoideo. O estado clínico resultante da alteração da função tireoidiana é classificado em hipotireoidismo (baixa função da tireoide) ou hipertireoidismo (função excessiva da tireoide). A exemplo da maioria das anormalidades endócrinas, a alteração da função tireoidiana pode ser genética ou adquirida, e sua duração pode ser transitória ou permanente.</p>', 'empty', 'empty', 0, 'falso'),
(132, 9, 7, '<p>Selecione a alternativa que não corresponde a uma consequência dos altos níveis de ACTH plasmático:</p>', 'Aumento da concentração de ácidos graxos no sangue', 'Estimulação da secreção de insulina', 'Aumento da produção de GH', 'Aumento da massa corporal', 'Aumento da concentração de glicerol no sangue', 'quest', '<p>O hormônio adrenocorticotrófico (ACTH) estimula as glândulas suprarrenais a produzir os hormônios esteróides, que regulam o equilíbrio da água e do sódio, a inflamação e o metabolismo. A liberação de ACTH é estimulada por estresses psicológicos e físicos, como infecção, hipoglicemia, cirurgia e traumatismo, sendo considerada de suma importância na mediação do estresse ou da resposta adaptativa do indivíduo ao estresse. O ACTH é liberado em pequenas quantidades, e os níveis circulantes são, em média, de 2 a 19 pmol/L em indivíduos sadios. O hormônio é liberado em pulsos, e as maiores concentrações são observadas em torno das 4 horas da manhã, enquanto as menores concentrações ocorrem à tarde. O cortisol, o principal glicocorticóide, exerce efeitos multissistêmicos, visto que praticamente todas as células expressam receptores de glicocorticóides. Os glicocorticóides, como o próprio nome sugere, desempenham um importante papel na regulação da homeostasia da glicose. Eles afetam o metabolismo intermediário, estimulam a proteólise e a gliconeogênese, inibem a síntese das proteínas musculares e aumentam a mobilização dos ácidos graxos. Seu efeito essencial consiste em aumentar os níveis de glicemia, daí sua designação de &ldquo;glicocorticoides&rdquo;. No fígado, eles aumentam a expressão das enzimas gliconeogênicas, como a fosfoenolpiruvato-carboxiquinase, a tirosina-aminotransferase e a glicose-6-fosfatase. No músculo, os glicocorticóides interferem na translocação do transportador de glicose 4 para a membrana plasmática.</p>', 'empty', 'empty', 4, ''),
(133, 10, 5, '<p>O hormônio antidiurético age sobre os rins, aumentando a retenção de líquidos corporais. Porém, sua liberação em excesso pode ocasionar Síndrome Inapropriada de ADH.</p><p>Sobre isso, selecione a alternativa que NÃO descreve um sinal da Síndrome Inapropriada de ADH:</p>', 'Oligúria (redução do volume urinário)', 'Urina muito concentrada ', 'Aumento da pressão arterial ', 'Hiponatremia dilucional ', 'Poliúria (urinar em excesso)', 'quest', '<p>O hormônio antidiurético (ADH) controla diretamente a excreção de água pelos rins. A secreção de ADH&nbsp;e a sede compensatória são estimuladas por osmorreceptores do hipotálamo e pela estimulação diminuída dos receptores de estiramento aórticos e carotídeos. A liberação de ADH é inibida por um aumento no estiramento dos mecanorreceptores (receptores de estiramento) nos átrios do coração. O ADH estimula a inserção das aquaporinas na membrana celular, aumenta a reabsorção de água nos ductos coletores e concentra a urina excretada.</p>', 'empty', 'empty', 5, ''),
(134, 10, 6, '<p>Qual das seguintes anormalidades têm mais tendência a ocorrer em consequência do comprometimento da ação do hormônio do crescimento?</p>', 'Baixo peso ao nascer e atraso do crescimento ', 'Incapacidade de dobrar o peso ao nascimento com seis meses de idade ', 'Baixa estatura em um menino de 12 anos ', 'Hiperglicemia de jejum e comprometimento da tolerância à glicose ', 'Voz grave e aumento dos pelos faciais', 'quest', '<p>O hormônio do crescimento (GH) exerce seus efeitos mais importantes sobre o crescimento longitudinal durante a infância. O crescimento intrauterino é modestamente afetado por níveis diminuídos de GH. De modo semelhante, o ganho de peso no início da vida pós-natal não depende da ação do GH. A hiperglicemia e o comprometimento da tolerância à glicose, bem como a voz mais grave, constituem manifestações da liberação excessiva de GH na vida adulta.</p>', 'empty', 'empty', 3, ''),
(135, 10, 7, '<p>A diabetes insipidus é uma doença caracterizada pela ausência da ação do hormônio antidiurético. Pode ser do tipo neurogênico (não ocorre a produção do ADH pelo hipotálamo) quanto do tipo nefrogênico (não há resposta renal ao ADH).</p><p>Selecione a alternativa que NÃO representa um sinal da diabetes insipidus:</p>', 'Urina muito concentrada', 'Poliúria (urinar em excesso)', 'Polidipsia (sede em excesso)', 'Hipovolemia (níveis muito baixos de plasma)', 'Hipotensão arterial', 'quest', '<p>O Diabete insípido&nbsp; caracteriza-se pela excreção de volumes anormalmente grandes de urina (30 mL/kg de peso corporal por dia em adultos) diluída (&lt; 250 mmol/kg) e por sede excessiva. Foram identificados três defeitos básicos em sua etiologia. Apenas os dois primeiros envolvem alterações relacionadas com os componentes do próprio sistema de AVP. No terceiro, o aporte excessivo de água não envolve alterações na liberação de ADH.</p>', 'empty', 'empty', 1, ''),
(136, 10, 9, '<p>O aumento excessivo de células da hipófise culmina &nbsp;no crescimento anormal da glândula, o que chamamos de tumor. Os motivos no qual levam a isso ainda não são conhecidos. Com isso, a secreção hormonal ficará irregular pode levar a sérias consequências. &nbsp;Qual das alternativas abaixo, não representa uma alteração da desregulação da hipófise?</p>', 'Náusea', 'Ganho de peso', 'Fraqueza', 'Melhora na disposição', 'Diminuição da libido', 'quest', '<p>Os tumores hipofisários podem resultar em produção hormonal deficiente ou excessiva. Com isso todos os hormônios que seriam secretados na região do tumor, poderão apresentar uma modulação positiva ou negativa. A pessoa poderá apresentar sintomas como por exemplo: fraqueza, cansaço excessivo, ganho de peso, enjoo e&nbsp;disfunção erétil.</p>', 'empty', 'empty', 4, ''),
(137, 1, 3, '<p>Fazem parte do eixo hipotálamo-hipófise o _______________, que participa no controle das funções vegetativas e endócrinas do organismo, a _____________, que é dividida em duas porções, a hipófise anterior, também chamada de _____________ e a hipófise posterior, também chamada de _______________.</p><p>Qual alternativa completa as lacunas corretamente?</p>', 'Hipófise, hipotálamo, adeno-hipófise, neuro-hipófise', 'Hipotálamo, hipófise, neuro-hipófise, adeno-hipófise', 'Neuro-hipófise, hipotálamo, adeno-hipófise, hipófise.', 'Hipotálamo, hipófise, adeno-hipófise, neuro-hipófise', 'Neuro-hipófise, hipófise, adeno-hipófise, hipotálamo', 'quest', '<p>O eixo hipotálamo-hipófise contém estruturas que serão responsáveis pela integração e distribuição dos sinais endócrinos. O hipotálamo por sua vez, será o grande centro integrador, já a hipófise anterior e posterior irão enviar os hormônios para seus respectivos órgãos-alvo.</p>', 'ajudab4574eaf5a308de0fa6ab3c68fd41292..jpg', 'empty', 4, ''),
(138, 1, 5, '<p>A ligação entre o hipotálamo e a porção anterior da hipófise acontece através do ____________________. Já a comunicação da parte posterior da hipófise com o hipotálamo acontece através de ________________.</p><p>Qual alternativa completa as lacunas corretamente?</p>', 'Sistema porta hipotalâmico-hipofisário, células neurossecretoras', 'Sistema límbico, fórnix', 'Sulco hipotalâmico, infundíbulo', 'Trato solitário, células neurossecretoras', 'Sistema porta hipotalâmico-hipofisário, infundíbulo', 'quest', '<p>Relações anatômicas e funcionais entre o hipotálamo e a hipófise. O hipotálamo está ligado, tanto anatômica quanto funcionalmente, à adeno-hipófise e à neuro-hipófise. Estão estreitamente relacionados devido ao sistema porta de suprimento sanguíneo. As artérias hipofisária superior, hipofisária medial e hipofisária inferior fornecem o suprimento sanguíneo arterial à eminência mediana e à hipófise. Os neurônios magnocelulares dos núcleos supraópticos (NSOs) e dos núcleos paraventriculares (NPVs) possuem axônios longos que terminam na neuro-hipófise.</p>', 'ajudaf1337cc4073a5c8eccfb273c94900c41..jpg', 'empty', 1, ''),
(139, 1, 7, '<p>As células neurossecretoras que fazem a comunicação entre o hipotálamo e a neuro-hipófise são os neurônios magnocelulares. Seus axônios não mielinizados&nbsp; formam o trato hipotalâmico-hipofisário que atravessa a parte medial, liberando hormônios na neuro-hipófise. Sobre a liberação de hormônios na neurohipófise, assinale a alternativa correta:</p>', 'Os hormônios são liberados através de vesículas', 'Os neurônios magnocelulares produzem ocitocina e GH', 'A liberação de hormônios acontece quando a neuro-hipófise é estimulada', 'Os hormônios são liberados na eminência mediana', 'Os neurônios magnocelulares são menores, se comparados aos parvicelulares', 'quest', '<p>Os neurônios magnocelulares são maiores e produzem grandes quantidades de neuro-hormônios. Localizados predominantemente nos núcleo paraventricular e supraóptico do hipotálamo, seus axônios não mielinizados formam o trato hipotalâmico-hipofisário que atravessa a eminência mediana, terminando na neuro-hipófise. Eles sintetizam os neuro-hormônios ocitocina e vasopressina, que são transportados em vesículas neurossecretoras pelo trato hipotálamo hipofisário e armazenados em varicosidades nas terminações nervosas da neuro-hipófise.</p>', 'empty', 'empty', 1, ''),
(140, 2, 2, '<p>Os neurônios parvicelulares estão localizados no hipotálamo. Suas projeções terminam na _______________, no ____________ e no ________________, onde irão liberar pequenas quantidades de neuro-hormônios que farão ativação ou inibição da atividade da adeno-hipófise. Qual alternativa completa corretamente as lacunas?</p>', 'Comissura posterior, corpo mamilar, infundíbulo', 'Eminência mediana, corpo mamilar, medula espinhal', 'Comissura posterior, tronco encefálico, infundíbulo', 'Eminência mediana, tronco encefálico, medula espinhal', 'Eminência mediana, corpo mamilar, medula espinhal', 'quest', '<p>Os neurônios parvicelulares são de tamanho pequeno e possuem projeções que terminam na eminência mediana, no tronco encefálico e na medula espinal. Eles liberam pequenas quantidades de neuro-hormônios de liberação ou de inibição (hormônios hipofisiotróficos), que controlam a função da adeno-hipófise.</p>', 'ajudad82eef4d7c10af5e5ebf791ebd5b2646..jpg', 'empty', 4, ''),
(141, 2, 3, '<p>Os neurônios parvicelulares secretam neuro-hormônios, que podem ser inibitórios ou estimulatórios. Estes, sinalizam células-alvo para secretar ou inibir seus respectivos hormônios. A liberação dos neuropeptídeos hipofisiotróficos, mantém um sistema integrado de controle da função endócrina através de um processo de retroalimentação.</p><p>Após ler essa afirmação, marque a alternativa&nbsp;&nbsp; que corresponde ao hormônios liberadores.</p>', 'ALRH, TRH, GNRH, PRH e CRH', 'GHRH, TRH, GNRH, QIRH e CRH', 'GHRH, TRH, GNRH, PRH e CRH', 'GHRH, ZRH, GNRH, PRH e CRH', 'GHRH, LCRH, ZRH, PRH e CRH', 'quest', '<p>Os neurônios parvicelulares irão secretar hormônios liberados na adeno-hipófise conforme for a necessidade do momento. Eles podem enviar sinais para inibir uma ação ou iniciar uma ação! são no total 5 hormônios liberadores, com a função de estimular uma célula alvo.</p>', 'empty', 'empty', 3, ''),
(142, 2, 4, '<p>A responsividade da adeno-hipófise aos efeitos inibitórios ou estimuladores dos neuro-hormônios hipofisiotróficos pode ser modificada por fatores, como os níveis hormonais, a inibição por retroalimentação negativa e os ritmos circadianos.</p>', '', '', '', '', '', 'vouf', '<p>A liberação dos hormônios adeno-hipofisários é de natureza cíclica, sendo esse padrão cíclico de liberação hormonal governado pelo sistema nervoso. Os ritmos são, em sua maioria, impulsionados por um relógio biológico interno localizado no núcleo supraquiasmático do hipotálamo. Sendo assim, todas as contribuições tanto positivas como negativas do ambiente interno ou externo, por exemplo o ciclo claro/escuro, poderão afetar um bom funcionamento da adeno-hipófise.</p>', 'empty', 'empty', 1, 'verdadeiro'),
(143, 2, 7, '<p>No hipotálamo, ainda encontramos neuro-hormônios que inibem as células na adeno-hipófise, sendo eles: (1) somatostatina, que terá como ação a inibição das células Somatotropos e tireotropos e&nbsp; (2) dopamina, que irá inibir a célula lactotrofos. Esta é uma afirmação verdadeira ou falsa?</p>', '', '', '', '', '', 'vouf', '<p>Na adeno-hipófise encontramos hormônios inibidores, que farão supressão da síntese de determinados hormônios. Estes neurônios têm suas fibras oriundas de diversas áreas do hipotálamo e têm suas fibras enviadas para a eminência mediana. na adeno-hipófise, a somatostatina e a dopamina estarão atuantes de forma agonista no bloqueio de três células do sistema endócrino e com isso, fazendo com que se tenha uma alça de feedback negativa em relação a ação principal do hormônio.</p>', 'empty', 'empty', 1, 'verdadeiro'),
(144, 3, 1, '<p>A adeno-hipófise secreta seis hormônios através de células específicas. Quais são eles? marque a alternativa correta.</p>', 'Hormônio do crescimento (GH), hormônio estimulante da tireoide (TSH), hormônio folículo estimulante (FSH), prolactina (PRL),  hormônio adrenocorticotrófico (ACTH)', 'Hormônio do crescimento (GH), ocitocina (OT), hormônio folículo estimulante (FSH), prolactina (PRL),  hormônio adrenocorticotrófico (ACTH)', 'Hormônio do crescimento (GH), hormônio estimulante da tireoide (TSH), hormônio folículo estimulante (FSH), prolactina (PRL),  vasopressina (ADH)', 'Hormônio do crescimento (GH), hormônio estimulante da tireoide (TSH), hormônio folículo estimulante (FSH), ocitocina (OT),  hormônio adrenocorticotrófico (ACTH)', 'Hormônio do crescimento (GH), vasopressina (ADH), hormônio folículo estimulante (FSH), prolactina (PRL),  hormônio adrenocorticotrófico (ACTH).', 'quest', '<p>A adeno-hipófise é uma estrutura muito potente que secreta hormônios que fundamentam a existência humana. Seis hormônios são enviados para o sistema através dessa parte da hipófise! porém, a ocitocina e o hormônio antidiurético, não fazem parte desse esquema hormonal.</p>', 'empty', 'empty', 1, ''),
(145, 3, 2, '<p>A hipófise posterior libera apenas dois hormônios. São eles: ocitocina e a vasopressina.</p>', '', '', '', '', '', 'vouf', '<p>Ocitocina e ADH são hormônios liberados pela neuro-hipófise.</p>', 'empty', 'empty', 1, 'verdadeiro'),
(146, 3, 3, '<p>Qual desses hormônios não é secretado pela adeno-hipófise?</p>', 'Hormônio do crescimento', 'Ocitocina', 'Prolactina', 'Adrenocorticotrofina', 'Hormônio folículo estimulante', 'quest', '<p>A adeno-hipófise secreta seis hormônios e a neuro-hipófise apenas dois! Arginina vasopressina e ocitocina fazem parte da hipófise posterior.</p>', 'empty', 'empty', 2, ''),
(147, 3, 4, '<p>&nbsp;Ocitocina e Vasopressina são hormônios oriundos do neurônio magnocelular.</p>', '', '', '', '', '', 'vouf', '', 'ajudaf349536ac52cefa42caf520285109535..jpg', 'empty', 1, 'verdadeiro'),
(148, 3, 5, '<p>A hipófise posterior, grande produtora de hormônios neuropeptídios, libera seu produto na forma de vesículas no terminal axonal. Após ler esta afirmação, marque a alternativa correta:</p>', 'O Produto não é enviado na forma de vesículas', 'A neuro-hipófise não produz hormônio', 'Os núcleos hipotalâmicos não participam deste processo', 'Os hormônios liberadores são protagonistas no processo', 'Todas as afirmações estão corretas', 'quest', '<p>Os neurônios magnocelulares também atuam na liberação dos hormônios da neuro-hipófise.</p>', 'empty', 'empty', 2, ''),
(149, 4, 1, '<p>O hormônio do crescimento (GH), também chamado de somatotrofina é secretado pela adeno-hipófise. Qual alternativa representa corretamente sua principal função?</p>', 'Estimular a liberação de insulina', 'Estimular a  secreção  de  T4  e  T 3  pela  glândula  tireoide', 'Estimular a produção de glicocorticoides', 'Estimular o crescimento e a multiplicação celular', 'Aumenta a retenção de água pelo corpo e a concentração de íons', 'quest', '<p>O hormônio do crescimento&nbsp; é liberado dos somatotropos, um tipo celular presente na adeno-hipófise em quantidades abundantes. A liberação ocorre em surtos pulsáteis, e a maior parte da secreção é noturna, ocorrendo em associação ao sono de ondas lentas. O GH tem uma importante função metabólica no nosso organismo, uma vez que é capaz de formar novos tecidos e com isso a melhora do trofismo muscular, por exemplo.</p>', 'empty', 'empty', 4, ''),
(150, 4, 4, '<p>Os níveis de GH circulante aumentam durante a infância, atingem seu pico durante a puberdade e diminuem com o envelhecimento. Após ler essa afirmação, marque a alternativa correta:</p>', '', '', '', '', '', 'vouf', '<p>O hormônio do crescimento não terá uma liberação linear durante o desenvolvimento do ser humano. A sua liberação será modulada conforme as fases que o indivíduo se encontra bem como suas necessidades metabólicas.</p>', 'empty', 'empty', 1, 'verdadeiro'),
(151, 4, 6, '<p>O hormônio estimulante da tireoide (TSH), que é secretado pela adeno-hipófise, estimula a tireoide a secretar o hormônio tiroxina (T3), que é convertido em triiodotironina (T4), o hormônio ativo que estimula o metabolismo.</p>', '', '', '', '', '', 'vouf', '<p>O hormônio tireoestimulante (TSH) é regulado pelo peptídeo hipofisiotrófico, o hormônio de liberação da tireotrofina (TRH). A produção dos hormônios da tireoide também é regulada pelo iodo da dieta. Os hormônios que irão modular o nosso metabolismo são respectivamente o triiodotironina e o tirosina, no qual um será convertido no outro conforme a necessidade metabólica.</p>', 'empty', 'empty', 0, 'falso'),
(152, 4, 7, '<p>A ativação do receptor de TSH resulta em estimulação de todas as etapas envolvidas na síntese dos hormônios da tireoide, incluindo a captação e a organificação do iodo, a produção e liberação de iodotironina pela glândula, e a promoção do crescimento da tireoide. Das alternativas abaixo qual não é uma etapa envolvida no processo da ativação do receptor do TSH?</p>', 'Captação de nutrientes', 'Estimular o processo de morte celular', 'Estimulação da transcrição gênica de fatores associados ', 'Regulação de processos metabólicos ', 'Síntese de hormônios', 'quest', '<p>O hormônio tireoestimulante irá fornecer subsídio para a ativação de toda a síntese dos hormônios da glândula tireoide.&nbsp; Como parte desse processo, o TSH regula a captação de nutrientes pela tireoide, bem como o transporte intracelular de proteínas específicas, envolvidas na síntese, no armazenamento e na liberação dos hormônios tireoidianos. Esses eventos celulares envolvem a regulação dos processos metabólicos celulares, a diferenciação morfológica, a proliferação das células e a proteção contra a apoptose. A apoptose (é um processo de morte celular programada) que acontece nos organismos pluricelulares que é fundamental para a homeostase.</p>', 'empty', 'empty', 2, ''),
(153, 4, 8, '<p>A elevação do AMPc induzida pela estimulação do TSH estimula o crescimento e a função da glândula tireoide.</p>', '', '', '', '', '', 'vouf', '<p>O TSH é transportado na corrente sanguínea até a glândula tireoide, onde se liga ao receptor de TSH localizado na membrana basolateral das células epiteliais foliculares da tireoide. O receptor de TSH é um receptor de membrana celular acoplado à proteína G. A função adequada desse receptor é de importância crítica para o desenvolvimento, o crescimento e a função da glândula tireoide. A ligação do TSH a seu receptor inicia o processo de sinalização por meio dos sistemas de transdução de sinais do monofosfato de 3&rsquo;,5&rsquo;-adenosina cíclico (AMPc, de cyclic 3&rsquo;,5&rsquo;-adenosine monophosphate), da fosfolipase C e da proteína-quinase A.</p>', 'empty', 'empty', 1, 'verdadeiro'),
(154, 4, 9, '<p>Outros mediadores neuroendócrinos que inibem a liberação de TSH incluem a __________, ______________ e ________________ que em altos níveis, provocam supressão parcial da liberação de TSH. Após ler a questão, marque a resposta que complete as lacunas acima.</p>', 'Somatostatina, dopamina, glicocorticoides', 'Acetilcolina, dopamina, glicocorticoides', 'Somatostatina, adrenalina, glicocorticoides', 'Acetilcolina, adrenalina, serotonina', 'Acetilcolina, adrenalina, glicocorticoides', 'quest', '<p>O TSH também poderá ser inibido com outros fatores neuroendócrinos. Os glicocorticoides são um exemplo, eles irão suprimir parcialmente a secreção do hormônio tireoestimulante, bem como, a somatostatina e a dopamina.</p>', 'empty', 'empty', 1, ''),
(155, 5, 1, '<p>O hormônio ______________________ (também chamado de corticotrofina) é produzido pela adeno-hipófise e sua liberação é controlada pelo hormônio liberador CRH.</p>', 'GH', 'Vasopressina', 'Ocitocina', 'Folículo estimulante', 'Adrenocorticotrófico', 'quest', '<p>A corticotrofina é um hormônio produzido pela hipófise anterior e tem como ativador o hormônio liberador de corticotrofina. Um outro nome para designar este hormônio é adrenocorticotrófico. Esse hormônio tem como órgão alvo o córtex da glândula suprarrenal, mais precisamente na zona fascicular que também produz o cortisol.</p>', 'empty', 'empty', 5, ''),
(156, 5, 2, '<p>A liberação de ACTH é estimulada por estresses psicológicos e físicos, como infecção, hipoglicemia, cirurgia e traumatismo, sendo considerada de suma importância na mediação do estresse ou da resposta adaptativa do indivíduo ao estresse. Marque a alternativa que denota um dos efeitos fisiológicos do ACTH.</p>', 'Contrações musculares uterinas', 'Estimulação do cortisol no córtex da suprarrenal', 'Estimula a libertação do leite materno', 'Aumenta a retenção de água pelo corpo', 'Estimula  a  produção  de glicocorticoides  e  androgênios', 'quest', '<p>A liberação de ACTH é pulsátil, com cerca de 7 a 15 episódios por dia. A estimulação da liberação de cortisol ocorre 15 minutos após o surto de ACTH. Uma importante característica da liberação do cortisol é o fato de que, além de ser pulsátil, ele segue um ritmo circadiano, peculiarmente sensível a fatores ambientais e internos, como luz, sono, estresse e alguma doença presente.</p>', 'empty', 'empty', 2, ''),
(157, 5, 3, '<p>A aldosterona, hormônio também liberado através da ativação do ACTH, tem como sua principal função o equilíbrio hidroeletrolítico.</p>', '', '', '', '', '', 'vouf', '<p>O equilíbrio hidroeletrolítico se dá quando os principais eletrólitos no corpo humano (sódio, potássio, cálcio, magnésio, cloro, fosfato, sulfato, bicarbonato, entre outros) estão dentro das taxas fixas necessárias para que possam exercer normalmente suas funções. o ADH colabora para que se tenha uma harmonia nesse sistema</p>', 'empty', 'empty', 1, 'verdadeiro'),
(158, 5, 4, '<p>As concentrações plasmáticas hormonais flutuam durante o dia. Por conseguinte, as determinações dos níveis plasmáticos hormonais nem sempre refletem a função de determinado sistema endócrino. Diversos fatores podem alterar a concentração de cortisol. Marque a alternativa que NÃO corresponde a um deles:</p>', 'Sono prejudicado ', 'Luz', 'Repouso prolongado no leito ', 'Sedentarismo', 'Presença de doença', 'quest', '<p>A liberação de ACTH é pulsátil, com cerca de 7 a 15 episódios por dia. A estimulação da liberação de cortisol ocorre 15 minutos após o surto de ACTH. Uma importante característica da liberação do cortisol é o fato de que, além de ser pulsátil, ele segue um ritmo circadiano, peculiarmente sensível a fatores ambientais e internos, como luz, sono, estresse e alguma doença presente.</p>', 'empty', 'empty', 4, ''),
(159, 5, 5, '<p>O cortisol exibe variações consideráveis dos seus níveis sanguíneos durante o dia. Sendo que, o seu pico de concentração acontece entre às 22:00 e às 23:00 com a finalidade de facilitar o sono.</p>', '', '', '', '', '', 'vouf', '<p>A liberação de cortisol é maior durante as primeiras horas de vigília, e os níveis declinam à medida que o dia prossegue. Em consequência de sua liberação pulsátil, os níveis circulantes do hormônio variam durante todo o dia, e isso tem um impacto direto na interpretação dos níveis de cortisol, com base na hora de coleta da amostra de sangue. Uma importante característica da liberação do cortisol é o fato de que, além de ser pulsátil, ele segue um ritmo circadiano, peculiarmente sensível a fatores ambientais e internos, como luz, sono, estresse e doenças existentes.</p>', 'empty', 'empty', 0, 'falso'),
(160, 6, 1, '<p>Os hormônios _________________ e ________________ são sintetizados e liberados através das células gonadotróficas da adeno-hipófise e seu principal papel é controlar a função _______________________ em ambos os sexos.</p>', 'Ocitocina, adrenalina, circulatória', 'Vasopressina, adrenocorticotrófico, renal', 'Folículo estimulante, luteinizante, reprodutivas', 'Acetilcolina, dopamina, cognitiva', 'Tireotrófico, triidotironina, da tireoide', 'quest', '<p>Os hormônios gonadotróficos LH e FSH são sintetizados e secretados pelos gonadotropos da adeno-hipófise em resposta à estimulação pelo hormônio de liberação das gonadotrofinas (GnRH). A maioria dos gonadotropos produz tanto LH quanto FSH, e uma fração da população dessas células sintetiza LH ou FSH, exclusivamente. O GnRH é sintetizado e secretado pelo hipotálamo de modo pulsátil. O FSH e o LH exercem seus efeitos fisiológicos sobre os testículos e os ovários por meio de sua ligação a receptores acoplados à proteína Gs e pela ativação da adenilato-ciclase. Entre as células-alvo das gonadotrofinas, destacam-se as células da granulosa do ovário, as células internas da teca, as células testiculares de Sertoli e as células de Leydig.</p>', 'ajudaf3a4e57f108ae739fcb4c6e58cc33ea7..jpg', 'empty', 3, ''),
(161, 6, 2, '<p>Assinale a alternativa que não indique um dos efeitos fisiológicos produzidos pelos hormônios gonadotróficos:</p>', 'Esteroidogênese (estimulação da síntese dos hormônios sexuais)', 'Espermatogênese (processo em que ocorre a formação e o desenvolvimento do espermatozoide)', 'Foliculogênese (Maturação do folículo ovariano)', 'Morte celular', 'Ovulação', 'quest', '<p>O FSH e o LH exercem seus efeitos fisiológicos sobre os testículos e os ovários por meio de sua ligação a receptores acoplados à proteína Gs e pela ativação da adenilato-ciclase. Entre as células-alvo das gonadotrofinas, destacam-se as células da granulosa do ovário, as células internas da teca, as células testiculares de Sertoli e as células de Leydig. As respostas fisiológicas produzidas pelas gonadotrofinas consistem na estimulação da síntese dos hormônios sexuais (esteroidogênese), espermatogênese, foliculogênese e ovulação. Por conseguinte, seu papel principal consiste em controlar a função reprodutiva em ambos os sexos.</p>', 'empty', 'empty', 4, ''),
(162, 6, 7, '<p>Existem duas fases no ciclo reprodutivo, sendo uma fase folicular, onde o FSH ___________________________________________ e uma fase lútea, onde o LH é responsável pela&nbsp; ________________________________________.</p>', 'Estimula  recrutamento e o crescimento dos folículos e a síntese de estrogênio / ovulação e pela formação do corpo lúteo, bem como pela produção de progesterona e estrogênio pelo corpo lúteo', 'Inibe a secreção de estrogênio / ovulação pelo corpo lúteo, bem como pela inibição de progesterona pelo corpo lúteo', 'Ovulação e pela formação do corpo lúteo, bem como pela produção de progesterona e estrogênio pelo corpo lúteo / estimula o recrutamento e o crescimento dos folículos e a síntese de estrogênio', 'Inibe o crescimento dos folículos e síntese de estrogênio / formação do corpo lúteo e produção de estrogênio e progesterona pelo corpo lúteo', 'Todas as alternativas estão erradas', 'quest', '<p>Durante a fase folicular, o FSH estimula o recrutamento e o crescimento dos folículos e a síntese de estrogênio. Antes da seleção do folículo para ovulação, as células da granulosa respondem apenas ao FSH. À medida que progride a maturação folicular, o acoplamento entre a estimulação dos receptores de FSH e a ativação da adenilato-ciclase torna-se cada vez mais eficiente, resultando em aumento uniforme na produção de AMPc. Já na fase lútea, o hormônio luteinizante é responsável pela ovulação e pela formação do corpo lúteo, bem como pela produção de progesterona e estrogênio pelo corpo lúteo. A ativação dos receptores de LH nas células da teca estimula a produção de androstenediona, fornecendo o substrato para a conversão enzimática em 17b-estradiol que é mediada pela aromatase nas células da granulosa.</p>', 'empty', 'empty', 1, ''),
(163, 6, 9, '<p>Sobre os principais hormônios femininos marque a alternativa que melhor corresponde as funções hormonais.</p>', 'A progesterona auxilia pouco na regulação do ciclo menstrual', 'A testosterona inexiste na mulher. É um hormônio apenas masculino', 'Estrogênio e progesterona são produzidos nos ovários durante a fase reprodutiva', 'Na ausência de fecundação, o estradiol aumenta', 'Nenhuma das alternativas', 'quest', '<p>A fase proliferativa corresponde à fase folicular do ovário. Caracteriza-se por proliferação das células epiteliais do endométrio induzida pelos estrogênios e regulação positiva da expressão dos receptores de estradiol e progesterona. A proliferação endometrial pré-ovulatória leva à hipertrofia relativa da mucosa uterina. Trata-se da fase inicial de maturação endometrial na preparação para a implantação do embrião.</p>', 'empty', 'empty', 3, '');
INSERT INTO `questoes` (`id`, `nivel`, `fase`, `texto`, `opcao1`, `opcao2`, `opcao3`, `opcao4`, `opcao5`, `categoria`, `textoajuda`, `fotoajuda`, `foto`, `correta`, `corretaVouf`) VALUES
(164, 7, 3, '<p>A principal função da arginina vasopressina consiste em aumentar a reabsorção de água e conservá-la.</p>', '', '', '', '', '', 'vouf', '<p>O principal efeito que o hormônio antidiurético tem no nosso corpo é a reabsorção de água. Isso ocorre através do aumento da permeabilidade à água nos túbulos convolutos distais e nos ductos coletores medulares do rim.</p>', 'ajudadbdde71a690e74046e4c1bc84dc7e6b2..jpg', 'empty', 1, 'verdadeiro'),
(165, 7, 5, '<p>A arginina vasopressina é liberada na circulação após um aumento da osmolaridade plasmática ou uma redução do volume sanguíneo.</p>', '', '', '', '', '', 'vouf', '<p>O mecanismo antidiurético poderá&nbsp; aumentar a osmolaridade urinária para cerca de 1.200 mmol/L e reduzir o fluxo urinário para cerca de 0,5 mL/min. Na ausência dos efeitos mediados pela arginina vasopressina, as células principais do ducto coletor são impermeáveis à água, resultando na entrada de grandes volumes de urina diluída nos túbulos coletores, provenientes do ramo ascendente da alça de Henle.</p>', 'empty', 'empty', 1, 'verdadeiro'),
(166, 7, 6, '<p>O hormônio ocitocina é produzido pelo hipotálamo e liberado pela neuro-hipófise. Dois fatores estimulam sua liberação, que são a ____________________________ e pela _____________________________ durante trabalho de parto.</p>', 'Liberação de testosterona / contrações', 'Fase lútea / distensão do colo do útero', 'Fase folicular / contrações', 'Sucção durante lactação / distensão do colo do útero', 'Liberação de estrogênio / contrações', 'quest', '<p>A mama em fase de lactação e o útero durante a gravidez constituem os dois principais órgãos-alvo dos efeitos fisiológicos da ocitocina. Na mama durante a lactação, a ocitocina estimula a ejeção do leite ao produzir contração das células mioepiteliais que revestem os alvéolos e os ductos da glândula mamária. No útero grávido, a ocitocina produz contrações rítmicas do músculo liso para ajudar a induzir o trabalho de parto e promover a regressão do útero após o parto.</p>', 'ajuda90dbac576ec50960107841ab9fada7c8..jpg', 'empty', 4, ''),
(167, 7, 7, '<p>A ocitocina atua sobre dois órgãos principais: a mama em fase de lactação e o útero durante a gravidez. Sua função nesses dois órgãos são, respectivamente, estimular a ejeção do leite e produzir contrações rítmicas do músculo liso para ajudar a induzir o trabalho de parto e promover a regressão do útero após o parto.</p>', '', '', '', '', '', 'vouf', '<p>A liberação de ocitocina é estimulada pela distensão do colo do útero na gravidez a termo e pela contração do útero durante o parto. Ele irá aumentar a sensibilidade à ocitocina e com isso, irá induzir e/ou facilitar o trabalho de parto. O aumento no número de receptores de ocitocina, o aumento no número das junções comunicantes (gap junctions) entre as células musculares lisas e o aumento na síntese das prostaglandinas intensificam a responsividade do músculo uterino. A sucção do mamilo da mama durante a lactação também estimula a liberação de ocitocina. Os sinais sensoriais aferentes desencadeiam um aumento na liberação de ocitocina na circulação.</p>', 'ajuda42866ad51876383e3dca9f8cfa2877b9..jpg', 'empty', 1, 'verdadeiro'),
(168, 7, 9, '<p>Quais são os neurotransmissores envolvidos no processo de liberação da ocitocina?</p>', 'Glutamato e acetilcolina', 'Adrenalina e dopamina', 'Gaba e acetilcolina', 'Glutamato e serotonina', 'Acetilcolina e dopamina', 'quest', '<p>A liberação de ocitocina também é desencadeada pela estimulação de receptores táteis nos mamilos da mama em fase de lactação durante a sucção. O aleitamento materno gera impulsos sensoriais que são transmitidos à medula espinhal e, a seguir, aos neurônios produtores de ocitocina no hipotálamo. A informação transmitida por esses aferentes sensoriais produz um surto sincronizado intermitente de descarga dos neurônios de ocitocina, resultando na liberação pulsátil de ocitocina e no aumento de suas concentrações no sangue. Acredita-se que os neurotransmissores envolvidos na estimulação da liberação de ocitocina sejam a acetilcolina e a dopamina.</p>', 'empty', 'empty', 5, ''),
(169, 8, 1, '<p>Sobre a glândula hipófise, marque a questão correta:</p>', 'A neuro-hipófise é a verdadeira região secretora de hormônios', 'A adeno-hipófise também é conhecida como hipófise posterior', 'A ocitocina, principal hormônio secretado pela neuro-hipófise, age diretamente nos rins, glândulas sudoríparas e arteríolas', 'A somatotrofina age principalmente no fígado', 'Os hormônios luteinizantes agem unicamente nos testículos', 'quest', '<p>O hipotálamo é a região do cérebro envolvida na coordenação das respostas fisiológicas de diferentes órgãos que, em seu conjunto, mantêm a homeostasia. Para desempenhar essa função, o hipotálamo integra os sinais provenientes do ambiente, de outras regiões do cérebro e de aferentes viscerais e, a seguir, estimula as respostas neuroendócrinas apropriadas. Dessa maneira, ele influência inúmeros aspectos da função diária, como a ingestão de alimentos, o consumo de energia, o peso corporal, a ingestão de líquido e o equilíbrio hídrico, a pressão arterial, a sede, a temperatura corporal e o ciclo do sono. Dentre todos os seu hormônios de grande importância nas respostas metabólicas, o hormônio do crescimento também conhecido como somatotropina, tem como um de seus papéis, estimular o fígado a produzir fatores de crescimento e a expressão genética do HGF (Hepatocyte growth factor) bem como a síntese de DNA.</p>', 'empty', 'empty', 4, ''),
(170, 8, 3, '<p>A neuro-hipófise é uma grande produtora de hormônios! Sendo mais produtiva que a adeno-hipófise.</p>', '', '', '', '', '', 'vouf', '<p>A adeno-hipófise, ou hipófise anterior, desempenha um papel fundamental na regulação da função endócrina, por meio da produção e da liberação dos hormônios tróficos. A função da adeno-hipófise e, consequentemente, a produção dos hormônios tróficos são reguladas pelo hipotálamo por meio dos neuropeptídeos hipofisiotróficos liberados na eminência mediana. A hipófise anterior produz seis hormônios enquanto a neuro-hipófise secreta apenas dois.</p>', 'empty', 'empty', 0, 'falso'),
(171, 8, 4, '<p>A hipófise secreta hormônios para determinados órgãos e glândulas que possuem funções vitais para o ser humano. Quais são eles?</p>', 'Glândula sudorípara, córtex da suprarrenal e Gônadas', 'Córtex da suprarrenal, Gônadas e Tireoide', 'Tireoide, testículos e Gônadas', 'Tireoide, Córtex da suprarrenal e Gônadas', 'Nenhuma das alternativas', 'quest', '<p>Os hormônios liberados pela adeno-hipófise e pela neuro-hipófise regulam funções orgânicas vitais para manter a homeostasia. Rim, fígado, tireóide, gônadas e testículos são alguns dos órgãos no qual irão ser estimulados intimamente pela secreção dos hormônios da hipófise.</p>', 'ajudad9debe4f91606dc5c2860df71719a4aa..jpg', 'empty', 4, ''),
(172, 8, 8, '<p>Os peptídeos hipotalâmicos liberados na eminência mediana são transportados até a adeno-hipófise, onde regulam a liberação dos hormônios adeno-hipofisários.</p>', '', '', '', '', '', 'vouf', '<p>O hipotálamo está ligado, tanto anatômica quanto funcionalmente, à adeno-hipófise e à neuro-hipófise. Estão estreitamente relacionados devido ao sistema porta de suprimento sanguíneo. As artérias hipofisária superior, hipofisária medial e hipofisária inferior fornecem o suprimento sanguíneo arterial à eminência mediana e à hipófise. Os neurônios magnocelulares dos núcleos supraópticos (NSOs) e dos núcleos paraventriculares (NPVs) possuem axônios longos que terminam na neuro-hipófise. Os axônios dos neurônios parvicelulares terminam na eminência mediana, onde liberam seus neuropeptídeos. As longas veias porta hipofisárias drenam a eminência mediana, transportando os peptídeos do plexo capilar primário para o plexo secundário, que fornece o suprimento sanguíneo à adeno-hipófise.</p>', 'empty', 'empty', 1, 'verdadeiro'),
(173, 9, 1, '<p>O gigantismo, doença que causa o crescimento excessivo do ser humano, é caracterizada pelo hipersecreção de qual hormônio?</p>', 'Hormônio luteinizante', 'Hormônio folículo-estimulante', 'Hormônio do crescimento', 'Hormônio antidiurético', 'Hormônio adrenocorticotrófico', 'quest', '<p>O adenoma hipofisário produtor de hormônio constitui a causa mais comum de produção excessiva de hormônios hipofisários. Os adenomas secretores de GH podem estar associados à acromegalia ou a um crescimento excessivo dos ossos e tecidos moles em adultos, bem como ao gigantismo nas crianças. Os adenomas com liberação de corticotrofina estão associados à produção excessiva de cortisol ou à síndrome de Cushing; os pacientes apresentam obesidade central, miopatia proximal, hipertensão, alterações do humor, coxim gorduroso dorsocervical e hiperglicemia, entre outros sinais e sintomas clínicos.</p>', 'ajuda2cfb13aa7a016e22057f1909373d5935..jpg', 'empty', 3, ''),
(174, 9, 2, '<p>A baixa secreção do GH poderá gerar qual tipo de transtorno?</p>', 'Acromegalia', 'Microcefalia', 'Nanismo pituitário', 'Gigantismo', 'Nenhuma das alternativas', 'quest', '<p>A deficiência de GH e o retardo do crescimento podem resultar de diminuição da liberação de GH pela hipófise devido a doenças do hipotálamo ou da hipófise, ou devido a uma predisposição genética. Alternativamente, a ocorrência de mutações no gene do receptor de GH pode causar insensibilidade ao GH e retardo do crescimento, com baixas concentrações séricas de IGF-1.</p>', 'ajuda3e10f74532d1fdad01e263ac0118071c..jpg', 'empty', 3, ''),
(175, 9, 3, '<p>A ocitocina, um dos hormônios da neuro-hipófise, poderá ser ofertado para a mãe na forma sintética para que seja facilitado o parto normal. Sendo assim, marque a questão que NÃO corresponderia a uma das funções desse hormônio:</p>', 'Redução do tônus uterino', 'Controle da hemorragia pós-parto', 'Auxílio na expulsão da placenta', 'Estimula a contração da musculatura lisa', 'Auxilia o útero a readquirir o seu tamanho normal', 'quest', '<p>A liberação de ocitocina é estimulada pela distensão do colo do útero na gravidez a termo e pela contração do útero durante o parto. Os sinais são transmitidos aos núcleos paraventriculares e supra ópticos do hipotálamo, onde asseguram a regulação da liberação de ocitocina por retroalimentação positiva. O aumento no número de receptores de ocitocina, o aumento no número das junções comunicantes (gap junctions) entre as células musculares lisas e o aumento na síntese das prostaglandinas intensificam a responsividade do músculo uterino. A sucção do mamilo da mama durante a lactação também estimula a liberação de ocitocina. Os sinais sensoriais aferentes desencadeiam um aumento na liberação de ocitocina na circulação.</p>', 'empty', 'empty', 1, ''),
(176, 9, 6, '<p>Não é uma característica de uma quadro de testosterona baixa:</p>', 'Menor desempenho sexual', 'Diminuição de pelos em geral', 'Depressão', 'Diminuição da massa corporal', 'Diminuição da gordura corporal', 'quest', '<p>A testosterona, sintetizada pelas células de Leydig, é o principal e mais importante androgênio testicular e circulante. O excesso de testosterona no indivíduo pré-púbere do sexo masculino está associado ao aparecimento de todas as alterações da puberdade em uma idade muito precoce. Essas alterações consistem em aumento do pênis e dos testículos; aparecimento dos pelos púbicos, axilares e faciais; ereções espontâneas; produção de espermatozoides; desenvolvimento de acne e mudança da voz. A deficiência de androgênios resulta em sintomas graves, que diferem de acordo com o momento de seu aparecimento. Quando ocorre no início da infância, resulta em baixa estatura, ausência de mudança da voz, distribuição feminina dos pelos secundários, anemia, músculos subdesenvolvidos e genitália com início tardio ou ausência da espermatogênese e da função sexual. A deficiência de androgênios no adulto, após o término do processo de virilização normal, leva a uma diminuição da densidade mineral óssea (massa óssea), redução da atividade da medula óssea com o consequente desenvolvimento de anemia, alterações da composição corporal associadas a fraqueza e atrofia musculares, alterações do humor e da função cognitiva, bem como regressão da função sexual e espermatogênese. No homem adulto, essa deficiência diminui as ereções noturnas e a libido.</p>', 'empty', 'empty', 5, ''),
(177, 9, 8, '<p>Alguns sinais da diminuição de ocitocina no organismo são:</p>', 'Palidez, estresse, obesidade e dores musculares', 'Aumento da massa corporal, dores musculares e tontura', 'Diminuição da massa corporal, emagrecimento e enjoo', 'Rubor, dores musculares e perda de função', 'Esquecimento, obesidade e aumento da massa corporal', 'quest', '<p>A ocitocina é um hormônio, produzido pelo hipotálamo e armazenado pela adeno-hipófise. O hipotálamo coordena as interações entre os neurônios e hormônios secretados pela glândula hipófise. A liberação do hipotálamo e os hormônios inibidores exercem seus efeitos sobre a liberação de hormônios hipofisários. A ocitocina e vasopressina (hormônio antidiurético) são liberados diretamente por axônios hipotalâmicos que terminam na hipófise posterior, e os hormônios são secretados de lá diretamente para a circulação sistêmica. Quando liberada perifericamente pela hipófise posterior, atua estimulando a produção de leite materno e a contração uterina no parto, já quando é liberada centralmente, a ocitocina age como um neuromodulador de diversos processos, tais como modulação da ansiedade, da libido, da interação social e regulação das respostas neuroendócrinas e cardiovasculares. A ocitocina tem sido alvo de novas pesquisas que relacionam a sua função na interação social e realização de vínculos afetivos. Quando esse hormônio se encontra em menor oferta, o nosso organismo poderá sofrer algumas consequências, sendo elas: dores musculares, obesidade, alterações no sono, estresse, palidez e diminuição da capacidade cognitiva.</p>', 'empty', 'empty', 1, ''),
(178, 9, 9, '<p>O estrogênio e a progesterona, que são regulados através dos hormônios gonadotróficos, em altos níveis nas mulheres, pode ser responsável pela retenção de líquido no organismo, o que por sua vez, causa inchaço.</p>', '', '', '', '', '', 'vouf', '<p>Quando temos os níveis de progesterona e estrogênio, alguns efeitos não genômicos poderão acontecer. Exemplos de alguns dos efeitos não genômicos rápidos dos estrogênios incluem efeitos diretos sobre a vascularização e a ativação das vias de sinalização relacionadas com fatores de crescimento. O estrogênio pode causar vasodilatação a curto prazo por vias tanto dependentes quanto independentes do endotélio. Ele produz vasodilatação a curto prazo e diminui o tônus do músculo liso vascular por meio de aumento na formação e na liberação do óxido nítrico e das prostaciclinas endoteliais, bem como pela abertura dos canais de cálcio mediada pelo monofosfato de guanosina cíclico (GMPc, de cyclic guanosine monophosphate). Em relação aos estrogênios, quando sua expressão gênica for alterada, se terá uma grande mudanças na resposta metabólica no corpo podendo afetar desde o sistema reprodutivo ao sistema nervoso central.</p>', 'empty', 'empty', 1, 'verdadeiro'),
(179, 10, 1, '<p>A síndrome de Cushing causa sintomas e complicações sérias como obesidade centrípeta, isto é, ocorre na face e no abdome, mas não nos membros que, ao contrário, são finos e com atrofia da musculatura, o que causa fraqueza muscular. Um dos precursores da doença é o aumento excessivo do cortisol. Sobre as síndrome de Cushing, marque a alternativa incorreta:</p>', 'Não tem cura', 'Aparecimento de estrias vermelhas', 'Diabetes', 'Hipertensão', 'Fraqueza muscular', 'quest', '<p>A manifestação clínica do excesso de glicocorticoides, conhecida como síndrome de Cushing, pode ser dividida em duas categorias, dependendo de sua etiologia. A síndrome de Cushing dependente de ACTH caracteriza-se por níveis elevados de glicocorticoides em consequência da estimulação excessiva pelo ACTH produzido por tumores hipofisários ou ectópicos (tecido extra-hipofisário). A fonte mais frequente de ACTH de produção ectópica é o carcinoma de pulmão de pequenas células. A secreção ectópica de ACTH em geral não é suprimida pela administração exógena de glicocorticoides (dexametasona), e essa característica é útil no diagnóstico diferencial. O termo &ldquo;doença de Cushing&rdquo; é reservado para a síndrome de Cushing causada pela secreção excessiva de ACTH por tumores hipofisários e constitui a forma mais comum da síndrome. Na síndrome de Cushing independente de ACTH, a produção excessiva de cortisol resulta de anormalidade na produção adrenocortical de glicocorticoides, independentemente da estimulação pelo ACTH. Com efeito, os níveis circulantes elevados de cortisol suprimem os níveis de CRH e de ACTH no plasma. Até então, ambas categorias da síndrome de cushing não apresentam cura! e sim, tratamento para controle da doença.</p>', 'empty', 'empty', 1, ''),
(180, 10, 2, '<p>A hiperprolactinemia se caracteriza pelo aumento excessivo do hormônio prolactina. Com ela, vem junto uma série de problemas tanto para as mulheres como para os homens. Sua causa pode ser fisiológica, farmacológica ou patológica. Dito isso, marque a resposta que mais se enquadra com as manifestações clínicas da hiperprolactinemia:</p>', 'Aumento da libido', 'Melhora na densidade óssea', 'Disfunção erétil', 'Função adequada da hipófise', 'Nenhuma das alternativas', 'quest', '<p>A hiperprolactinemia é a alteração endócrina mais comum do eixo hipotalâmico-hipofisário, predominando no sexo feminino. Sua prevalência varia de 0,4% em uma população não selecionada de adultos normais a valores tão altos quanto 9-17% em mulheres com distúrbios reprodutivos. A dosagem de prolactina (PRL) sérica atualmente tem indicações cada vez mais amplas que incluem a presença de alterações menstruais, amenorréia, infertilidade e galactorréia em mulheres, bem como o manuseio de homens com disfunção erétil e infertilidade. Além disso, é de fundamental importância na investigação e seguimento dos tumores da região selar. Na determinação da etiologia da hiperprolactinemia e na interpretação da dosagem da PRL, é preciso estar atento a algumas armadilhas que podem levar a um diagnóstico incorreto e, consequentemente, a um manuseio inadequado.</p>', 'empty', 'empty', 3, ''),
(181, 10, 3, '<p>Durante a fase folicular do ciclo menstrual, se tem o FSH como sinalizador do início da fase e o aumento da progesterona.</p>', '', '', '', '', '', 'vouf', '<p>A liberação de gonadotrofinas é regulada, por meio de retroalimentação negativa e positiva, pelo estradiol, pela progesterona e pelas inibinas A e B. Tanto a progesterona quanto o 17b-estradiol atuam no hipotálamo e na hipófise, enquanto as inibinas atuam no nível da hipófise. As contribuições desses hormônios ovarianos variam de acordo com o estágio do ciclo ovariano. Durante essa fase, o folículo dominante produz altas concentrações de 17b-estradiol e inibina B. Embora inicialmente o estradiol exerça um efeito de retroalimentação negativa sobre a liberação de FSH e LH, à medida que as concentrações de estradiol aumentam, no final da fase folicular, observa-se uma mudança de retroalimentação negativa para positiva. Os altos níveis de estradiol no hipotálamo e na hipófise levam a pulsos de baixa amplitude e alta frequência (a cada 90 minutos) de LH, resultando no surto de LH na metade do ciclo.</p>', 'empty', 'empty', 1, 'verdadeiro'),
(182, 10, 4, '<p>A ocitocina sintética é utilizada na hora do parto para auxiliar em todo o processo fazendo com que se tenha a expulsão do bebê e com isso diminuir o trabalho de parto.</p><p>Sendo assim, marque a alternativa que melhor explica&nbsp; o enunciado acima:</p>', 'Diminuição do tônus uterino, por isso o bebê irá sair mais rápido', 'Aumento do sangramento na hora do parto, melhorando a vascularização local', 'Melhora da contratilidade uterina', 'Deixa o colo do útero menor, facilitando a passagem do bebê', 'Nenhuma das alternativas acima', 'quest', '<p>A mama em fase de lactação e o útero durante a gravidez constituem os dois principais órgãos-alvo dos efeitos fisiológicos da ocitocina. Na mama durante a lactação, a ocitocina estimula a ejeção do leite ao produzir contração das células mioepiteliais que revestem os alvéolos e os ductos da glândula mamária. No útero grávido, a ocitocina produz contrações rítmicas do músculo liso para ajudar a induzir o trabalho de parto e promover a regressão do útero após o parto. Análogos da ocitocina, a ocitocina sintética, podem ser usados clinicamente durante o trabalho de parto e o parto para promover as contrações uterinas, bem como durante o período pós-parto para ajudar a diminuir o sangramento e propiciar o retorno do útero a seu tamanho normal (involução uterina).</p>', 'empty', 'empty', 3, '');

--
-- Índices para tabelas despejadas
--

--
-- Índices para tabela `questoes`
--
ALTER TABLE `questoes`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `questoes`
--
ALTER TABLE `questoes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=183;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
